### ISSUE TITLE
Potential Database Security Flaw

### ISSUE THREAD

**Issue by mechastriker3** [steffy-lo/animania#4]
Hi, I stumbled upon this repo and upon further inspection of the code in app.py there is a potential major security leak. You left the whole connection string to cloud mongodb in the app.py(in line 15) The connection string also includes your unhashed password and username. With the connection string I'm able to connect to your mongodb cloud instance. 
I'm guessing the mongodb cloud instance is not IP whitelisted properly and hence I'm able to connect to it from another IP that is not your application frontend.
I'm also speculating that this database is on a throwaway account hence you guys might have overlooked this issue but it might be worth mentioning in the README.md so that potential users of this repo are aware of this issue

**Comment by steffy-lo** [comment]
Hi, really thanks for pointing that out. There wasn't really any sensitive information in the database, but I'll remove my mongo uri from the app.py anyways.Much thanks!On Jul. 18, 2020 6:03 a.m., mechastriker3 <notifications@github.com> wrote:
Hi, I stumbled upon this repo and upon further inspection of the code in app.py there is a potential major security leak. You left the whole connection string to cloud mongodb in the app.py(in line 15) The connection string also includes your unhashed password and username. With the connection string I'm able to connect to your mongodb cloud instance.
I'm guessing the mongodb cloud instance is not IP whitelisted properly and hence I'm able to connect to it from another IP that is not your application frontend.
I'm also speculating that this database is on a throwaway account hence you guys might have overlooked this issue but it might be worth mentioning in the README.md so that potential users of this repo are aware of this issue
